### PR TITLE
Laboratory Work #4, Alborova Alina, 17FPL-2

### PR DESCRIPTION
**Pull request by alinaalborova**

### CODE REVIEW

**Comment by mafatekhov** [comment]
@alinaalborova broken indentation in line 92, 'TfIdfCalculator' object has no attribute 'file_names'

**Comment by mafatekhov** [comment]
8, 9 if you fix dump function

**Comment by alinaalborova** [comment]
@mafatekhov Right! I've fixed it.

**Comment by mafatekhov** [comment]
9

**Pull request closed without merging**
